#Snakemake home folder:
mainfolder: /home/ubuntu/EukBook
# Working directory (may be overwritten with command line option -d)
workdir: /mnt/samples/simple

# Snakemake will create subfolders with following program version names
# to avoid overwriting old results if different version of program is used.
megahit_version: megahit_v1.2.9
EukRep_version: EukRep_v0.6.6
EukRep_mode: lenient
MetaEuk_version: MetaEuk_alpha
MetaEuk_reference: metaeuk_ref_profiles_more_than1_MMETSP_zenodo_3247846_profiles
MetaEuk_taxAnnot: MMETSP_zenodo_3247846_uniclust90_2018_08_seed_valid_taxids

# Pipeline running settings:
Quick_mode: False 
Megahit_parallel_mode: True
targetmail: dembra96@gmail.com
